#!/usr/bin/env bash

set -euo pipefail

assets_dir="$HOME/.config/hypr/assets"
state_dir="$HOME/.config/hypr/hyprpaper"
state_file="$state_dir/persistent-wallpaper.conf"

if [[ ! -d "$assets_dir" ]]; then
  exit 0
fi

for bin in wofi hyprctl jq; do
  if ! command -v "$bin" >/dev/null 2>&1; then
    exit 1
  fi
done

mapfile -d '' files < <(
  find "$assets_dir" -maxdepth 1 -type f \
    \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.webp' -o -iname '*.gif' -o -iname '*.bmp' -o -iname '*.avif' -o -iname '*.jxl' \) \
    -print0 | sort -z
)

if (( ${#files[@]} == 0 )); then
  exit 0
fi

entries=()
for file in "${files[@]}"; do
  entries+=("img:$file:text:${file##*/}")
done

selected_entry="$(
  printf '%s\n' "${entries[@]}" | wofi --dmenu --allow-images --insensitive --cache-file /dev/null --prompt 'Wallpaper' --define image_size=96
)"
if [[ -z "${selected_entry:-}" ]]; then
  exit 0
fi

if [[ "$selected_entry" == img:*":text:"* ]]; then
  selected_path="${selected_entry#img:}"
  selected_path="${selected_path%%:text:*}"
else
  selected_path="$assets_dir/$selected_entry"
fi

if [[ ! -f "$selected_path" ]]; then
  exit 0
fi

mapfile -t monitors < <(hyprctl monitors -j 2>/dev/null | jq -r '.[] | select(.disabled != true) | .name' 2>/dev/null)
if (( ${#monitors[@]} == 0 )); then
  exit 1
fi

applied=0
for monitor in "${monitors[@]}"; do
  if hyprctl hyprpaper wallpaper "$monitor,$selected_path,cover" >/dev/null 2>&1; then
    applied=1
  fi
done

if (( applied == 0 )); then
  exit 1
fi

mkdir -p "$state_dir"
tmp_file="$(mktemp)"
{
  echo "# Auto-generated by wallpaper-picker.sh"
  echo "# Do not edit manually."
  echo "preload = $selected_path"
  for monitor in "${monitors[@]}"; do
    echo "wallpaper = $monitor, $selected_path"
  done
} > "$tmp_file"
mv "$tmp_file" "$state_file"
