#!/usr/bin/env bash

set -euo pipefail

wallpaper_path="${1:-}"
target_monitor="${2:-All}"
hyprpaper_config="$HOME/.config/hypr/hyprpaper/hyprpaper.conf"
state_file="$HOME/.config/hypr/hyprpaper/persistent-wallpaper.conf"

if [[ -z "$wallpaper_path" ]]; then
  exit 1
fi

if [[ ! -f "$wallpaper_path" ]]; then
  exit 1
fi

if ! pgrep -x hyprpaper >/dev/null 2>&1; then
  hyprpaper -c "$hyprpaper_config" &
  sleep 1
fi

if [[ "$target_monitor" == "All" ]]; then
  mapfile -t monitors < <(hyprctl monitors -j | jq -r '.[] | select(.disabled != true) | .name')
else
  monitors=("$target_monitor")
fi

if (( ${#monitors[@]} == 0 )); then
  exit 1
fi

hyprctl hyprpaper unload all >/dev/null 2>&1 || true
hyprctl hyprpaper preload "$wallpaper_path" >/dev/null 2>&1 || true

applied=0
for monitor in "${monitors[@]}"; do
  if hyprctl hyprpaper wallpaper "$monitor,$wallpaper_path,cover" >/dev/null 2>&1; then
    applied=1
  fi
done

if (( applied == 0 )); then
  exit 1
fi

tmp_file="$(mktemp)"
{
  echo "# Auto-generated by waypaper-apply.sh"
  echo "# Do not edit manually."
  echo "preload = $wallpaper_path"
  for monitor in "${monitors[@]}"; do
    echo "wallpaper = $monitor, $wallpaper_path"
  done
} > "$tmp_file"
mv "$tmp_file" "$state_file"
